name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./ui
          build: yarn build
          start: yarn serve -s dist

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ui/cypress/screenshots
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: ui/cypress/videos
          if-no-files-found: error
